In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datetime import datetime

In [6]:
PATH = '/home/disk/orca/adaley17/MLGEO2024_TC_Tracks_Intensity/data/clean/'
AI_Ready_Path = '/home/disk/orca/adaley17/MLGEO2024_TC_Tracks_Intensity/data/ai_ready/'
bt_file = 'cleaned_SHIPS_data.csv'

df_SHIPS = pd.read_csv(PATH + bt_file)

In [10]:
df_SHIPS = df_SHIPS.loc[:, df_SHIPS.columns != 'Unnamed: 0']
df_SHIPS.head()

,Original_Times,Original_Lat,Original_Lon,Original_WSPD,Original_Pres,Name,Code,Times,Latitude,Longitude,Vmax,MSLP,Nature,Delta_Intensity,Daily_SST_Avg,Mid_Level_RH,Vshear,Vert_Vel
0,1982-06-02 12:00:00,21.7,87.1,10.28888,1005.0,ALBE,AL011982,-12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1982-06-02 12:00:00,21.7,87.1,10.28888,1005.0,ALBE,AL011982,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1982-06-02 12:00:00,21.7,87.1,10.28888,1005.0,ALBE,AL011982,0.0,21.7,87.1,10.28888,1005.0,1.0,0.0,27.1,57.0,15.227542,6.631183
3,1982-06-02 12:00:00,21.7,87.1,10.28888,1005.0,ALBE,AL011982,6.0,22.2,86.5,12.86110,1004.0,0.0,5.0,27.8,53.0,15.536209,3.966363
4,1982-06-02 12:00:00,21.7,87.1,10.28888,1005.0,ALBE,AL011982,12.0,22.6,85.8,15.43332,1003.0,0.0,10.0,27.9,56.0,15.330431,4.403641

The data consist of 18 columns and 318550 rows. The rows are labelled as follows:

1. Original Times - The initial time at which the forecast was made
2. Original Lat - The initial latitudinal position of the storm
3. Original Lon - The initial logitudinal position of the storm
4. Original Wind Speed - The initial wind speed of the storm
5. Original Minimum Sea level Pressure - The initial minimum sea level pressure
6. Name - The name of the storm being forecasted
7. Code - The unique identifier of each storm (Names are repeated hence the unique identifier)
8. Times - The forescated periods (for each initial time the storm is forecasted up to 120 hrs ahead at 6hr intervals)
9. Latitude - The forecsated latitude position at each 6hr interval
10. Longitide - The forecasted longitude position at each 6hr interval
11. Maximum Wind Speed - The forecasted peak winds at each 6hr interval
12. Minimum Sea level Pressure - The forecasted minimum sea level pressure at each 6hr interval
13. Nature - Storm type (0=wave, remnant low, dissipating low, 1=tropical, 2=subtropical, 3=extratropical) at forecasted interval
14. Delta Intensity - The forecasted change in intensity at each 6hr interval (Intensity is characterised by changes in wind speed)
15. Avergae Daily SST - spatially averaged over 5 points (storm center, + 50 km N, E, S and W of center)
16. Mid Level Relative Humidity - The forecasted mid level relative humidity (%) vs time (200-800 km) 850 - 700 hPa
17. Vertical Shear - The forecasted vertical environmental shear for each 6 hr interval (850-200 hPa shear magnitude (kt *10) vs time (takes into account all levels from 1000 to 100 hPa ))
18. Vertical Velocity - forecasted vertical velocity at 6hr intervals (Average (0 to 15 km) vertical velocity (m/s * 100) of a parcel lifted from the surface where entrainment, the ice phase and the condensate weight are accounted for.)

In [12]:
df_SHIPS.to_csv(AI_Ready_Path + 'ai_ready_SHIPS_data.csv', index=False)